### PR TITLE
Quote fieldnames, so fields named such as "binary" can be used

### PR DESCRIPTION
**Pull request by akarelas**

### CODE REVIEW

**Comment by jhthorsen** [comment]
Sounds like a sane change, but I would like a test, so I don't accidentally change the defaults again.

Maybe you can add something like the code below to https://github.com/jhthorsen/mojo-mysql/blob/master/t/connection.t ?

```
like $mysql->abstract->select("foo", ['binary']), qr{`binary`}, 'quoted correct';
```

**Comment by akarelas** [comment]
`prove -vl` fails on Mojo::mysql (your master branch), should I worry?

```
t/migrations.t ............ 
ok 1 - right name
ok 2 - latest version is 0
ok 3 - active version is 0
ok 4 - migrations table does not exist
ok 5 - active version is 0
ok 6 - migrations table exists
ok 7 - latest version is 0
ok 8 - latest version is 0
ok 9 - latest version is 10
ok 10 - latest version is 2
ok 11 - latest version is 10
ok 12 - latest version is 2
ok 13 - latest version is 10
ok 14 - active version is 0
ok 15 - active version is 10
not ok 16 - right structure

#   Failed test 'right structure'
#   at t/migrations.t line 65.
Wide character in print at /home/karjala/perl5/lib/perl5/Test2/Formatter/TAP.pm line 105.
#     Structures begin differing at:
#          $got->{foo} = 'works ?'
#     $expected->{foo} = 'works ♥'
ok 17 - active version is 10
DBD::mysql::st execute failed: Illegal mix of collations (latin1_swedish_ci,IMPLICIT) and (utf8_general_ci,COERCIBLE) for operation '=' at /home/karjala/modules/mojo-mysql/lib/Mojo/mysql/Migrations.pm line 128.
# Tests were run but no plan was declared and done_testing() was not seen.
# Looks like your test exited with 255 just after 17.
Dubious, test returned 255 (wstat 65280, 0xff00)
Failed 1/17 subtests 
t/mysql_auto_reconnect.t .. 
ok 1 - connected
ok 2 - mysql_auto_reconnect=0
1..2
ok
t/mysql_lite_app.t ........ [Sat May 13 06:12:51 2017] [debug] GET "/app_test"
[Sat May 13 06:12:51 2017] [debug] Template "not_found.development.html.ep" not found
[Sat May 13 06:12:51 2017] [debug] Template "not_found.html.ep" not found
[Sat May 13 06:12:51 2017] [debug] Rendering template "mojo/debug.html.ep"
[Sat May 13 06:12:51 2017] [debug] Rendering template "mojo/menubar.html.ep"
[Sat May 13 06:12:51 2017] [debug] Your secret passphrase needs to be changed
[Sat May 13 06:12:51 2017] [debug] 404 Not Found (0.06013s, 16.631/s)

ok 1 - GET /app_test
ok 2 - 404 Not Found
[Sat May 13 06:12:51 2017] [debug] GET "/blocking"
[Sat May 13 06:12:51 2017] [debug] Routing to a callback
[Sat May 13 06:12:51 2017] [debug] 200 OK (0.003452s, 289.687/s)
ok 3 - GET /blocking
ok 4 - 200 OK
not ok 5 - exact match for content

#   Failed test 'exact match for content'
#   at t/mysql_lite_app.t line 38.
Wide character in print at /home/karjala/perl5/lib/perl5/Test2/Formatter/TAP.pm line 105.
#          got: 'I ? Mojolicious!'
#     expected: 'I ♥ Mojolicious!'
[Sat May 13 06:12:51 2017] [debug] GET "/blocking"
```

**Comment by akarelas** [comment]
Test added, as you requested, jhthorsen

**Comment by Tekki** [comment]
Don't you think you should test something like
``like $mysql->abstract->select('foo', ['foo.binary']), qr{`foo`\.`binary`}, 'quoted correct';``
?

**Comment by akarelas** [comment]
Just added Tekki's test as well

**Comment by jhthorsen** [comment]
It's really bad that the test is failing... It would be "acceptable" if it was just locally for you, but I don't like that it's failing at travis as well.

(Pretty sure the tests are not failing because of this PR)

Unfortunately, I don't have time to look at this today. Will hopefully look at it on Monday.

**Comment by jhthorsen** [comment]
Looks like there was a change in DBD::mysql which caused the failing test. I've fixed that now.

Thanks everyone!

**Pull request merged**
