### PR TITLE
Added missing prereq DBI as suggested by CPANTS.

### PR DESCRIPTION
**Pull request by manwar**
Hi @jhthorsen 

Please review the PR.
https://cpants.cpanauthors.org/release/TEKKI/Mojo-mysql-1.15

Many Thanks.
Best Regards,
Mohammad S Anwar

### CODE REVIEW

**Review by jhthorsen — CHANGES_REQUESTED** [review]
Thanks for the PR 👍 

I don't understand how DBD::mysql does not depend on DBI.

Anyways, I think if we depend on DBI, we should have a minimum version number. How about 1.609, since that's what DBD::mysql seems to have in Makefile.PL and it's later than what DBD::MariaDB require. Or 1.627, since it's available in Centos7. Both are quite old, but I haven't read the Changelog thoroughly enough to say if we need any more recent.

**Comment by Tekki** [comment]
I think this test produces some false alerts. For [Mojolicious](https://cpants.cpanauthors.org/release/SRI/Mojolicious-8.14) for example it complains about EV and Sub::Util.

**Comment by jhthorsen** [comment]
@Tekki: Thanks for the insight! I don't mind adding DBI as a prereq though, since it is something that is needed for the Mojo::mysql to work.

**Comment by Grinnz** [comment]
It is because DBI is explicitly used (https://github.com/jhthorsen/mojo-mysql/blob/master/lib/Mojo/mysql.pm#L5) and the test does not know if you can rely on the DBD::mysql dependency to provide this (even though we know logically it must). Also it is nice to have the separate dependency in case Mojo::mysql needs a specific version of DBI that DBD::mysql doesn't.

**Comment by jhthorsen** [comment]
So what does that conclude on? Please add thumbs up/down on this:

```
requires 'DBI' => 1.627;
```

**Comment by Tekki** [comment]
What speaks against adding DBD::MariaDB too?
```
requires 'DBI' => 1.627;
requires 'DBD::MariaDB' => 1.21;
requires 'DBD::mysql' => '4.042';
```

**Comment by jhthorsen** [comment]
> What speaks against adding DBD::MariaDB too?

I don't think we'll ever get done with this PR if we start discussing that as well. Please open an issue where you suggest that, or replacing DBD::mysql with DBD::MariaDB as default, or something else. I really don't want to mix these two discussions here.

**Comment by Grinnz** [comment]
> ```
> requires 'DBI' => 1.627;
> ```

Quoted like the other versions :)

**Comment by jhthorsen** [comment]
@manwar: Care to update the PR with the suggested version number?

**Comment by manwar** [comment]
Updated as suggested.
Please review again when you get time.

**Review by jhthorsen — APPROVED** [review]

**Comment by jhthorsen** [comment]
Thank you! 👍

**Pull request merged**
