### PR TITLE
Add missing code for SQL JOIN

### PR DESCRIPTION
**Pull request by Tekki**
Changes for #54. Now this should be the correct PR.

### CODE REVIEW

**Review by jhthorsen — CHANGES_REQUESTED** [review]
I think this is a great improvement, but I don’t want do/while loops.

Also, did you run the code through perltidy?

**Comment by Tekki** [comment]
Yes, I ran perltidy. And I don't want do...while loops either.

**Comment by Tekki** [comment]
Does it look better now?

**Review by jhthorsen — APPROVED** [review]
Yes. Looks good :)

**Pull request merged**
