### PR TITLE
migrations parser

### PR DESCRIPTION
**Pull request by harry-bix**
- support for delimiter
- correct split of sql statements
- ';' or other defined delimiter in quotes and comments
- possible to define stored procedures and triggers in migration scripts

### CODE REVIEW

**Comment by jhthorsen** [comment]
What is the reason for this PR? What does it add?

**Comment by harry-bix** [comment]
It is a bugfix and enhancement.
Migration scripts were failing if the delimiter (;) was contained in quotes or comments.
The enhancement is the custom **delimiter** command just like in the mysql client.
**delimiter** command allows definition of stored procedures or triggers in migration scripts.
More complex parser was needed in place of split(';', $sql)

**Comment by harry-bix** [comment]
https://dev.mysql.com/doc/refman/5.6/en/mysql-commands.html

https://dev.mysql.com/doc/refman/5.6/en/stored-programs-defining.html

**Comment by jhthorsen** [comment]
Cool. Thanks for explaining.

**Pull request merged**
