### PR TITLE
fixed "(in cleanup) Can't call method "FETCH" on an undefined value"

### PR DESCRIPTION
**Pull request by kberov**
...during global destruction.

### CODE REVIEW

**Comment by jhthorsen** [comment]
Thanks. I will have a look at this next week, unless @harry-bix beats me to it.

**Comment by kberov** [comment]
:+1: Thanks, I am not sure tough while the tests are failing, Looks like some configuration stuff rather than real fails

**Comment by jhthorsen** [comment]
Pretty sure it's real fails. Seing the same thing locally with the patch.

**Comment by jhthorsen** [comment]
Can you provide an example (test?) where this error is seen?

**Comment by jhthorsen** [comment]
Closing this because of inactivity.

**Pull request closed without merging**
